# Generated by Django 5.2.1 on 2025-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_messagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatus',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
