# Generated by Django 5.2.1 on 2025-05-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_messagestatus_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='YookassaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=1024)),
                ('number', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
