# Generated by Django 5.2.1 on 2025-05-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_yookassainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yookassainfo',
            name='bucked_id',
            field=models.IntegerField(default=0),
        ),
    ]
