EXAMINATION_SUB_TEXT = 'Чтобы использовать бота, войдите в группу и подпишитесь на канал'
EXAMINATION_SUBMIT_TEXT = '✅Готово'
EXAMINATION_CHANEL_TEXT = '📣Канал'
EXAMINATION_GROUP_TEXT = '💬Группа'

MENU_TEXT = '👋Приветствую вас'
GO_MENU_TEXT = 'В меню'
CATALOG_BUTTON_TEXT = 'Каталог'
BUCKED_BUTTON_TEXT = 'Корзина'
FAQ_BUTTON_TEXT = 'FAQ'

CATALOG_TEXT = '🎒Добро пожаловать в каталог'
BACK_BUTTON_TEXT = '<<'
FRONT_BUTTON_TEXT = '>>'
SUBCATEGORY_TEXT = 'Подкатегория: '
GO_CATEGORYES_BTN_TEXT = 'Категории'
GET_ITEM_IN_BUCKED = 'Добавить в корзину'
PLUS_ITEM_TEXT = '+1'
MINUS_ITEM_TEXT = '-1'
SUBMIT_ITEM_TEXT = 'Подтвердить'
CHANGE_ITEM_TEXT = 'Изменить'
EMPTY_BUCKED_TEXT = 'Ваша корзина пуста'
BUCKED_SUBMIT_TEXT = 'Подтвердить покупку'
BUCKED_DELETE_ITEM = 'Удалить из корзины'
NUMBER_TEXT = 'Введите номер телефона для доставки'
ADRESS_TEXT = 'Введите точный адресс'
PAY_SUBMIT = 'Оплатить'
PAY_CHANGE_DATA = 'Изменить данные'